version: '0.1'
paths:
  specs: specs
  aips: aips
  templates: config/templates/specs
  schemas: config/schemas
repo:
  default_branch: main
current:
  spec: specs/test-claude-integration-simple.md
  aip: /home/user/specwright/aips/test-claude-integration-simple.yaml
