version: '0.1'
paths:
  specs: specs
  aips: aips
  templates: config/templates/specs
  schemas: config/schemas
repo:
  default_branch: main
current:
  spec: specs/upgrade-to-include-hitl-steps-and-auditsignoff-interactive-console.md
  aip: /home/user/specwright/aips/meltano-ingest-cloudrun-dispatcher-initial-spec.yaml
